import{a as v,S,i as c}from"./assets/vendor-D0cagnvz.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();async function g(o=1){return(await v("https://pixabay.com/api/",{params:{key:"29882819-d1b2e59da7ad20757f8559035",q:d,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:h}})).data}function m(o){return o.map(({webformatURL:t,largeImageURL:a,tags:s,likes:e,views:r,comments:n,downloads:L})=>`<li class="photo-card">
          <a href="${a}" class="link">
          <img src="${t}" alt="${s}" class="photo-card-img"/></a>
          <div class="info">
          <p class="info-item">Likes: <b>${e}</b></p>
          <p class="info-item">Views: <b>${r}</b></p>
          <p class="info-item">Comments: <b>${n}</b></p>
          <p class="info-item">Downloads:<b>${L}</b></p>
          </div>
       
        </li>`).join("")}const p=document.querySelector(".gallery"),w=document.querySelector(".search-form"),l=document.querySelector(".loader"),u=document.querySelector(".js-guard");console.log(u);let d,i=1,h=15,y=new S(".gallery a",{captionsData:"alt",captionDelay:300});const P={root:null,rootMargin:"0px",threshold:0};w.addEventListener("submit",q);const f=new IntersectionObserver(H,P);function q(o){if(o.preventDefault(),d=o.target.elements.searchQuery.value.trim(),d===""){c.warning({message:"Please enter some data",position:"topRight"});return}d&&(i=1),p.innerHTML="",l.classList.remove("hidden"),g(i).then(t=>{if(t.hits.length){p.insertAdjacentHTML("beforeend",m(t.hits));const s=document.querySelector(".photo-card").getBoundingClientRect();b(s),y.refresh(),t.totalHits<h||i===Math.ceil(t.totalHits/h)?f.unobserve(u):f.observe(u)}else c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}).catch(t=>{console.log(t),c.error({message:"Sorry, there are some problems with connection. Please reload the page and try again!",position:"topRight"})}).finally(()=>{o.target.elements.searchQuery.value="",l.classList.add("hidden")})}function b(o){window.scrollBy({top:2*o.height,left:0,behavior:"smooth"})}function H(o,t){o.forEach(a=>{a.isIntersecting&&(i+=1,l.classList.remove("hidden"),g(i).then(s=>{p.insertAdjacentHTML("beforeend",m(s.hits));const r=document.querySelector(".photo-card").getBoundingClientRect();b(r),y.refresh(),i===Math.ceil(s.totalHits/h)&&(l.classList.add("hidden"),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),t.unobserve(u))}).catch(s=>{console.log(s),c.error({message:"Sorry, there are some problems with connection. Please reload the page and try again!",position:"topRight"})}).finally(()=>{l.classList.add("hidden")}))})}
//# sourceMappingURL=index.js.map
