import{S as L,i as c}from"./assets/vendor-5ObWk2rO.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function h(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=h(e);fetch(e.href,r)}})();function m(o){return o.map(({webformatURL:t,largeImageURL:h,tags:a,likes:e,views:r,comments:i,downloads:y})=>`<li class="photo-card">
          <a href="${h}" class="link">
<img src="${t}" alt="${a}" height="250" width="350"/></a>
          <div class="info">
          <p class="info-item">Likes: <b>${e}</b></p>
          <p class="info-item">Views: <b>${r}</b></p>
          <p class="info-item">Comments: <b>${i}</b></p>
          <p class="info-item">Downloads:<b> ${y}</b></p>
          </div>

        </li>`).join("")}const f=document.querySelector(".gallery"),b=document.querySelector(".search-form"),l=document.querySelector(".loader"),n=document.querySelector(".js-load");let s=1,p=new L(".gallery a",{captionsData:"alt",captionDelay:300}),u;n.classList.add("hidden");b.addEventListener("submit",w);n.addEventListener("click",P);const S="29882819-d1b2e59da7ad20757f8559035",d=new URLSearchParams({key:S,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:16});function g(o=1){return fetch(`https://pixabay.com/api/?${d}&page=${s}`).then(t=>{if(!t.ok)throw new Error(t.statusText);return t.json()})}function w(o){if(o.preventDefault(),u=o.target.elements.searchQuery.value.trim(),u===""){c.warning({message:"Please enter some data",position:"topRight"});return}d.set("q",u),f.innerHTML="",l.classList.remove("hidden"),g(s).then(t=>{t.hits.length?(console.log(d.toString()),f.insertAdjacentHTML("beforeend",m(t.hits)),p.refresh()):(n.classList.add("hidden"),c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}))}).catch(t=>{console.log(t),n.classList.add("hidden"),c.error({message:"Sorry, there are some problems with connection. Please reload the page and try again!",position:"topRight"})}).finally(()=>{o.target.elements.searchQuery.value="",l.classList.add("hidden")}),n.classList.remove("hidden")}function P(){console.log(s),s=s+1,l.classList.remove("hidden"),g(s).then(o=>{console.log(d.toString()),f.insertAdjacentHTML("beforeend",m(o.hits)),p.refresh()}).catch(o=>{console.log(o),c.error({message:"Sorry, there are some problems with connection. Please reload the page and try again!",position:"topRight"})}).finally(()=>{l.classList.add("hidden")})}
//# sourceMappingURL=index.js.map
