import{S as b,i as a,a as L}from"./assets/vendor-D0cagnvz.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function h(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=h(e);fetch(e.href,t)}})();function u(r){return r.map(({webformatURL:o,largeImageURL:h,tags:c,likes:e,views:t,comments:i,downloads:y})=>`<li class="photo-card">
          <a href="${h}" class="link">
<img src="${o}" alt="${c}" height="250" width="350"/></a>
          <div class="info">
          <p class="info-item">Likes: <b>${e}</b></p>
          <p class="info-item">Views: <b>${t}</b></p>
          <p class="info-item">Comments: <b>${i}</b></p>
          <p class="info-item">Downloads:<b> ${y}</b></p>
          </div>

        </li>`).join("")}const p=document.querySelector(".gallery"),v=document.querySelector(".search-form"),n=document.querySelector(".loader"),d=document.querySelector(".js-load");let l,s=1,f=15,m=new b(".gallery a",{captionsData:"alt",captionDelay:300});v.addEventListener("submit",S);d.addEventListener("click",P);async function g(r=1){return(await L("https://pixabay.com/api/",{params:{key:"29882819-d1b2e59da7ad20757f8559035",q:l,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:f}})).data}function S(r){if(r.preventDefault(),l=r.target.elements.searchQuery.value.trim(),l===""){a.warning({message:"Please enter some data",position:"topRight"});return}l&&(s=1),p.innerHTML="",n.classList.remove("hidden"),g(s).then(o=>{o.hits.length?(p.insertAdjacentHTML("beforeend",u(o.hits)),m.refresh(),d.classList.remove("hidden")):a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}).catch(o=>{console.log(o),a.error({message:"Sorry, there are some problems with connection. Please reload the page and try again!",position:"topRight"})}).finally(()=>{r.target.elements.searchQuery.value="",n.classList.add("hidden")}),d.classList.add("hidden")}function P(){s+=1,n.classList.remove("hidden"),g(s).then(r=>{p.insertAdjacentHTML("beforeend",u(r.hits)),m.refresh(),s===Math.ceil(r.totalHits/f)&&(n.classList.add("hidden"),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),d.classList.add("hidden"))}).catch(r=>{console.log(r),a.error({message:"Sorry, there are some problems with connection. Please reload the page and try again!",position:"topRight"})}).finally(()=>{n.classList.add("hidden")})}
//# sourceMappingURL=index.js.map
